services:
  construct:
    restart: always
    expose:
      - 3000
    pull_policy: always
    networks:
      - coolify
    image: ghcr.io/hackclub/construct:production

networks:
  coolify:
    external: true