services:
  construct:
    restart: always
    expose:
      - 3000
    env_file:
      - .env
    pull_policy: always
    networks:
      - coolify
    image: ghcr.io/hackclub/construct:staging

networks:
  coolify:
    external: true